### ISSUE TITLE
a crash with the mod AdventureZ

### ISSUE THREAD

**Issue by jklw10** [WittyWhiscash/DamageOverhaul#2]
[crash-2021-03-13_12.47.24-server.txt](https://github.com/WittyWhiscash/DamageOverhaul/files/6134609/crash-2021-03-13_12.47.24-server.txt)

**Comment by WittyWhiscash** [comment]
Thank you for reporting!

It appears the logic I put in my mixin is returning incorrectly. Specifically, because I simply check to see if the attacker is "not null", and in this case, not "in my database" as well, it's performing logic as if the Ork, which appears to not be in the database judging by the crash, has a database entry. 

What it SHOULD be doing is performing normal Minecraft damage logic if the mob does not have a database entry. 

I'm going to push a fix here in the next day or so.

**Comment by WittyWhiscash** [comment]
Should be fixed in version `1.0.0-BETA2`. Reopen this issue if it still persists.
